define({ "height":10,
 "layers":[
        {
         "data":[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         "height":10,
         "name":"Background",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":10,
         "x":0,
         "y":0
        }, 
        {
         "data":[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 8, 8, 8, 8, 8, 8, 8, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         "height":10,
         "name":"Ground",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":10,
         "x":0,
         "y":0
        }, 
        {
         "height":10,
         "name":"Objects",
         "objects":[
                {
                 "height":32,
                 "name":"Goal",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":256,
                 "y":80
                }, 
                {
                 "height":32,
                 "name":"StartPosition",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":32,
                 "y":80
                }, 
                {
                 "gid":18,
                 "height":0,
                 "name":"Block1",
                 "properties":
                    {

                    },
                 "type":"Pushable",
                 "visible":true,
                 "width":0,
                 "x":96,
                 "y":112
                }, 
                {
                 "gid":16,
                 "height":0,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"Hole",
                 "visible":true,
                 "width":0,
                 "x":192,
                 "y":112
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "width":10,
         "x":0,
         "y":0
        }],
 "orientation":"orthogonal",
 "properties":
    {

    },
 "tileheight":32,
 "tilesets":[
        {
         "firstgid":1,
         "image":"..\/..\/..\/..\/src\/js-games\/LD30\/images\/tileset.png",
         "imageheight":64,
         "imagewidth":128,
         "margin":0,
         "name":"tileset",
         "properties":
            {

            },
         "spacing":0,
         "tileheight":32,
         "tilewidth":32
        }, 
        {
         "firstgid":9,
         "image":"..\/..\/..\/..\/src\/js-games\/LD30\/images\/tileset2.png",
         "imageheight":64,
         "imagewidth":160,
         "margin":0,
         "name":"props",
         "properties":
            {

            },
         "spacing":0,
         "tileheight":32,
         "tilewidth":32
        }],
 "tilewidth":32,
 "version":1,
 "width":10
})
