define({ "height":10,
 "layers":[
        {
         "data":[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         "height":10,
         "name":"Background",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":10,
         "x":0,
         "y":0
        }, 
        {
         "data":[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 8, 8, 8, 8, 8, 8, 8, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         "height":10,
         "name":"Ground",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":10,
         "x":0,
         "y":0
        }, 
        {
         "height":10,
         "name":"Objects",
         "objects":[
                {
                 "height":64,
                 "name":"Goal",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":64,
                 "x":512,
                 "y":160
                }, 
                {
                 "height":64,
                 "name":"StartPosition",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":64,
                 "x":64,
                 "y":160
                }, 
                {
                 "gid":18,
                 "height":0,
                 "name":"Block1",
                 "properties":
                    {

                    },
                 "type":"Pushable",
                 "visible":true,
                 "width":0,
                 "x":192,
                 "y":256
                }, 
                {
                 "gid":16,
                 "height":0,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"Hole",
                 "visible":true,
                 "width":0,
                 "x":384,
                 "y":224
                }, 
                {
                 "gid":18,
                 "height":0,
                 "name":"Block1",
                 "properties":
                    {

                    },
                 "type":"Pushable",
                 "visible":true,
                 "width":0,
                 "x":192,
                 "y":192
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "width":10,
         "x":0,
         "y":0
        }],
 "orientation":"orthogonal",
 "properties":
    {

    },
 "tileheight":64,
 "tilesets":[
        {
         "firstgid":1,
         "image":"images\/tileset.png",
         "imageheight":128,
         "imagewidth":256,
         "margin":0,
         "name":"tileset",
         "properties":
            {

            },
         "spacing":0,
         "tileheight":64,
         "tilewidth":64
        }, 
        {
         "firstgid":9,
         "image":"images\/tileset2.png",
         "imageheight":128,
         "imagewidth":320,
         "margin":0,
         "name":"props",
         "properties":
            {

            },
         "spacing":0,
         "tileheight":64,
         "tilewidth":64
        }],
 "tilewidth":64,
 "version":1,
 "width":10
})
