define ({ "height":16,
 "layers":[
        {
         "data":[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4, 4, 0, 0, 0, 4, 4, 0, 0, 0, 4, 4, 4, 4, 4, 4, 8, 8, 8, 4, 4, 0, 0, 0, 4, 4, 4, 4, 4, 8, 0, 0, 0, 8, 8, 0, 0, 0, 8, 8, 4, 8, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 8, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 8, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 8, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 8, 8, 8, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         "height":16,
         "name":"Ground",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":14,
         "x":0,
         "y":0
        }, 
        {
         "data":[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0],
         "height":16,
         "name":"Background",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":14,
         "x":0,
         "y":0
        }, 
        {
         "data":[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 13, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         "height":16,
         "name":"Pushable",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":14,
         "x":0,
         "y":0
        }, 
        {
         "height":16,
         "name":"Start",
         "objects":[
                {
                 "height":64,
                 "name":"StartPosition",
                 "properties":
                    {

                    },
                 "type":"StartPosition",
                 "visible":true,
                 "width":64,
                 "x":640,
                 "y":896
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "width":14,
         "x":0,
         "y":0
        }, 
        {
         "height":16,
         "name":"Goal",
         "objects":[
                {
                 "height":64,
                 "name":"Goal",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":64,
                 "x":704,
                 "y":192
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "width":14,
         "x":0,
         "y":0
        }, 
        {
         "height":16,
         "name":"Triggers",
         "objects":[
                {
                 "gid":9,
                 "height":64,
                 "name":"Trigger1",
                 "properties":
                    {
                     "triggerId":"dark1"
                    },
                 "type":"Trigger",
                 "visible":true,
                 "width":64,
                 "x":448,
                 "y":832
                }, 
                {
                 "gid":9,
                 "height":64,
                 "name":"Trigger2",
                 "properties":
                    {
                     "triggerId":"dark2"
                    },
                 "type":"Trigger",
                 "visible":true,
                 "width":64,
                 "x":192,
                 "y":704
                }, 
                {
                 "gid":9,
                 "height":64,
                 "name":"Trigger3",
                 "properties":
                    {
                     "triggerId":"dark3"
                    },
                 "type":"Trigger",
                 "visible":true,
                 "width":64,
                 "x":192,
                 "y":320
                }, 
                {
                 "gid":9,
                 "height":64,
                 "name":"Trigger4",
                 "properties":
                    {
                     "triggerId":"dark4"
                    },
                 "type":"Trigger",
                 "visible":true,
                 "width":64,
                 "x":128,
                 "y":192
                }, 
                {
                 "gid":9,
                 "height":64,
                 "name":"Trigger5",
                 "properties":
                    {
                     "triggerId":"dark5"
                    },
                 "type":"Trigger",
                 "visible":true,
                 "width":64,
                 "x":256,
                 "y":192
                }, 
                {
                 "gid":9,
                 "height":64,
                 "name":"Trigger6",
                 "properties":
                    {
                     "triggerId":"dark1"
                    },
                 "type":"Trigger",
                 "visible":true,
                 "width":64,
                 "x":512,
                 "y":832
                }, 
                {
                 "gid":9,
                 "height":64,
                 "name":"Trigger7",
                 "properties":
                    {
                     "triggerId":"dark2"
                    },
                 "type":"Trigger",
                 "visible":true,
                 "width":64,
                 "x":256,
                 "y":704
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "width":14,
         "x":0,
         "y":0
        }, 
        {
         "height":16,
         "name":"Blocks",
         "objects":[
                {
                 "gid":12,
                 "height":64,
                 "name":"Block1",
                 "properties":
                    {
                     "triggerId":"light1"
                    },
                 "type":"ToggleBlock",
                 "visible":true,
                 "width":64,
                 "x":320,
                 "y":768
                }, 
                {
                 "gid":12,
                 "height":64,
                 "name":"Block2",
                 "properties":
                    {
                     "triggerId":"light2"
                    },
                 "type":"ToggleBlock",
                 "visible":true,
                 "width":64,
                 "x":128,
                 "y":320
                }, 
                {
                 "gid":12,
                 "height":64,
                 "name":"Block3",
                 "properties":
                    {
                     "triggerId":"light3"
                    },
                 "type":"ToggleBlock",
                 "visible":true,
                 "width":64,
                 "x":256,
                 "y":320
                }, 
                {
                 "gid":12,
                 "height":64,
                 "name":"Block4",
                 "properties":
                    {
                     "triggerId":"light4"
                    },
                 "type":"ToggleBlock",
                 "visible":true,
                 "width":64,
                 "x":64,
                 "y":256
                }, 
                {
                 "gid":12,
                 "height":64,
                 "name":"Block5",
                 "properties":
                    {
                     "triggerId":"light5"
                    },
                 "type":"ToggleBlock",
                 "visible":true,
                 "width":64,
                 "x":192,
                 "y":192
                }, 
                {
                 "gid":12,
                 "height":64,
                 "name":"Block6",
                 "properties":
                    {
                     "triggerId":"light6"
                    },
                 "type":"ToggleBlock",
                 "visible":true,
                 "width":64,
                 "x":320,
                 "y":256
                }, 
                {
                 "gid":12,
                 "height":64,
                 "name":"Block7",
                 "properties":
                    {
                     "triggerId":"light1"
                    },
                 "type":"ToggleBlock",
                 "visible":true,
                 "width":64,
                 "x":384,
                 "y":768
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "width":14,
         "x":0,
         "y":0
        }, 
        {
         "height":16,
         "name":"Holes",
         "objects":[
                {
                 "gid":16,
                 "height":64,
                 "name":"Hole1",
                 "properties":
                    {

                    },
                 "type":"Hole",
                 "visible":true,
                 "width":64,
                 "x":192,
                 "y":512
                }, 
                {
                 "gid":16,
                 "height":64,
                 "name":"Hole2",
                 "properties":
                    {

                    },
                 "type":"Hole",
                 "visible":true,
                 "width":64,
                 "x":448,
                 "y":256
                }, 
                {
                 "gid":16,
                 "height":64,
                 "name":"Hole3",
                 "properties":
                    {

                    },
                 "type":"Hole",
                 "visible":true,
                 "width":64,
                 "x":512,
                 "y":256
                }, 
                {
                 "gid":16,
                 "height":64,
                 "name":"Hole4",
                 "properties":
                    {

                    },
                 "type":"Hole",
                 "visible":true,
                 "width":64,
                 "x":576,
                 "y":256
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "width":14,
         "x":0,
         "y":0
        }],
 "orientation":"orthogonal",
 "properties":
    {

    },
 "tileheight":64,
 "tilesets":[
        {
         "firstgid":1,
         "image":"images\/tileset.png",
         "imageheight":128,
         "imagewidth":256,
         "margin":0,
         "name":"tileset",
         "properties":
            {

            },
         "spacing":0,
         "tileheight":64,
         "tilewidth":64
        }, 
        {
         "firstgid":9,
         "image":"images\/tileset2.png",
         "imageheight":128,
         "imagewidth":320,
         "margin":0,
         "name":"tileset2",
         "properties":
            {

            },
         "spacing":0,
         "tileheight":64,
         "tilewidth":64
        }],
 "tilewidth":64,
 "version":1,
 "width":14
})